name: Test

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go 1.23
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'
    
    - name: Set up docker
      uses: docker/setup-buildx-action@v2
    
    - name: Install golang-migrate
      run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
    
    - name: Install go dependencies
      run: go mod tidy
    
    - name: Create .env.test file from secrets
      run: |
        echo "POSTGRES_URL=${{ secrets.POSTGRES_URL }}" > .env.test
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env.test
    
    - name: Make scripts executable
      run: chmod -R +x ./scripts
    
    - name: Run tests
      run: sudo make test